[build]
  publish = "build"
  command = "CI= npm run build"

[build.environment]
  NODE_VERSION = "18"
  CI = "false"

[[redirects]]
  from = "/api/*"
  to = "https://jw-transport.onrender.com/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  external_node_modules = ["sqlite3"]

[dev]
  command = "npm start"
  port = 3000
  publish = "build"
